import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";
import { AgentRun, Project, Requirement, RunEvent, Task, TestResult, User, api } from "./api";

type Nav = (path: string) => void;
type Route = { name: string; id?: string; projectId?: string };
const future = ["流程工作台","审查中心","文档中心","Agent 管理","代码评审","PR / MR 看板","测试中心","运维中心","知识库","集成中心","系统配置","用户权限"];
const routeOf = (path: string): Route => {
  let match; if (path === "/login") return {name:"login"}; if (path === "/") return {name:"dashboard"}; if (path === "/projects") return {name:"projects"};
  if ((match=path.match(/^\/projects\/([^/]+)\/requirements\/new$/))) return {name:"newRequirement",projectId:match[1]};
  if ((match=path.match(/^\/projects\/([^/]+)$/))) return {name:"project",id:match[1]};
  if ((match=path.match(/^\/requirements\/([^/]+)$/))) return {name:"requirement",id:match[1]};
  if ((match=path.match(/^\/tasks\/([^/]+)$/))) return {name:"task",id:match[1]};
  if ((match=path.match(/^\/runs\/([^/]+)$/))) return {name:"run",id:match[1]};
  return {name:"coming"};
};
const err = (value: unknown) => value instanceof Error ? value.message : "发生未知错误";
const labels: Record<string,string> = {pending:"待开始",todo:"待开始",queued:"排队中",running:"执行中",waiting_confirmation:"待确认",succeeded:"执行成功",completed:"已完成",failed:"失败",cancelled:"已取消"};
function Status({value="pending"}:{value?:string}) { return <span className={`status status-${value}`}>{labels[value]||value}</span>; }
function Button({children,variant="",busy,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:string;busy?:boolean}) { return <button className={`button ${variant}`} disabled={busy||props.disabled} {...props}>{busy?<><i className="spinner small"/>处理中</>:children}</button>; }
function Loading({text="正在加载数据..."}:{text?:string}) { return <div className="loading"><i className="spinner"/>{text}</div>; }
function ErrorBox({message,retry}:{message:string;retry?:()=>void}) { return <div className="error-box"><div><b>加载失败</b><p>{message}</p></div>{retry&&<Button onClick={retry}>重新加载</Button>}</div>; }
function Empty({title,detail,action}:{title:string;detail:string;action?:ReactNode}) { return <div className="empty"><i>◇</i><h3>{title}</h3><p>{detail}</p>{action}</div>; }
function Header({title,desc,action,back}:{title:string;desc?:string;action?:ReactNode;back?:()=>void}) { return <div className="page-header"><div>{back&&<button className="back" onClick={back}>← 返回</button>}<h1>{title}</h1>{desc&&<p>{desc}</p>}</div>{action}</div>; }

function Login({done}:{done:(user:User)=>void}) {
  const [email,setEmail]=useState("admin@example.com"),[password,setPassword]=useState("admin123"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{done((await api.login(email,password)).user)}catch(x){setError(err(x))}finally{setBusy(false)}}
  return <main className="login"><section className="login-hero"><div className="hero-logo">F</div><h1>从产品想法到可运行代码</h1><p>使用 AI 串联需求、文档、任务、开发和测试，快速完成软件交付闭环。</p><div>想法 <b>→</b> PRD <b>→</b> 任务 <b>→</b> Agent <b>→</b> 测试</div></section><form className="login-card" onSubmit={submit}><div className="brand-inline"><i>F</i><b>FlowMind</b></div><h2>欢迎回来</h2><p>登录 AI 全栈开发平台</p>{error&&<div className="form-error">{error}</div>}<label>邮箱</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label>密码</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button variant="primary block" busy={busy}>登录平台</Button><small>演示账号由后端环境配置</small></form></main>;
}
function Layout({user,route,nav,logout,children}:{user:User;route:Route;nav:Nav;logout:()=>void;children:ReactNode}) {
  return <div className="shell"><aside className="sidebar"><div className="brand"><i>F</i><div><b>FlowMind</b><small>AI FULL-STACK PLATFORM</small></div></div><nav><label>研发工作台</label><button className={route.name==="dashboard"?"active":""} onClick={()=>nav("/")}><i>⌂</i>Dashboard</button><button className={["projects","project","newRequirement","requirement","task","run"].includes(route.name)?"active":""} onClick={()=>nav("/projects")}><i>▣</i>项目管理</button><label>研发协作</label>{future.slice(0,8).map((x,n)=><button key={x} onClick={()=>nav(`/coming-soon?module=${encodeURIComponent(x)}`)}><i>{["⌘","✓","▤","◉","⌁","⑂","⚗","♢"][n]}</i>{x}</button>)}<label>平台管理</label>{future.slice(8).map(x=><button key={x} onClick={()=>nav(`/coming-soon?module=${encodeURIComponent(x)}`)}><i>◇</i>{x}</button>)}</nav><div className="user"><span>{user.name?.[0]||"管"}</span><div><b>{user.name}</b><small>{user.role||"管理员"}</small></div><button onClick={logout}>↪</button></div></aside><section className="workspace"><header className="topbar"><b>AI 全栈开发平台 <span>/</span> {route.name==="dashboard"?"Dashboard":"研发工作台"}</b><div><em>● MVP 模式</em><i>{user.name?.[0]}</i></div></header><main className="content">{children}</main></section></div>;
}

function Dashboard({nav}:{nav:Nav}) {
  const [projects,setProjects]=useState<Project[]>([]),[tasks,setTasks]=useState<Task[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const list=await api.projects();setProjects(list);setTasks((await Promise.all(list.map(p=>api.tasks(String(p.id)).catch(()=>[])))).flat())}catch(x){setError(err(x))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
  if(loading)return <><Header title="Dashboard" desc="查看研发进展，快速开启新的 AI 开发任务"/><Loading/></>; if(error)return <ErrorBox message={error} retry={load}/>;
  const data=[["项目总数",projects.length,"▣","purple"],["研发任务",tasks.length,"✓","blue"],["执行中",tasks.filter(t=>["queued","running"].includes(t.status)).length,"◉","orange"],["已完成",tasks.filter(t=>t.status==="completed").length,"◆","green"]];
  return <><Header title="Dashboard" desc="查看研发进展，快速开启新的 AI 开发任务" action={<Button variant="primary" onClick={()=>nav("/projects")}>＋ 新建需求</Button>}/><div className="metrics">{data.map(x=><div className="metric" key={String(x[0])}><i className={String(x[3])}>{x[2]}</i><div><span>{x[0]}</span><b>{x[1]}</b></div></div>)}</div><div className="dashboard-grid"><section className="card span-2"><div className="card-head"><div><h2>最近项目</h2><p>继续推进已有项目</p></div><button onClick={()=>nav("/projects")}>查看全部 →</button></div>{projects.length?<div className="rows">{projects.slice(0,5).map(p=><button key={p.id} onClick={()=>nav(`/projects/${p.id}`)}><i>{p.name[0]}</i><span><b>{p.name}</b><small>{p.description||"暂无描述"}</small></span><em>查看详情 →</em></button>)}</div>:<Empty title="还没有项目" detail="创建第一个项目，开启 AI 开发闭环" action={<Button variant="primary" onClick={()=>nav("/projects")}>创建项目</Button>}/>}</section><section className="card"><div className="card-head"><div><h2>任务概览</h2><p>最近生成的开发任务</p></div></div>{tasks.length?<div className="mini-tasks">{tasks.slice(0,6).map(t=><button key={t.id} onClick={()=>{sessionStorage.setItem(`task:${t.id}`,JSON.stringify(t));nav(`/tasks/${t.id}`)}}><span><b>{t.title}</b><small>任务 #{t.id}</small></span><Status value={t.status}/></button>)}</div>:<Empty title="暂无研发任务" detail="提交需求并生成研发资产后会显示在这里"/>}</section></div></>;
}

function Projects({nav}:{nav:Nav}) {
  const [items,setItems]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{setItems(await api.projects())}catch(x){setError(err(x))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const p=await api.createProject({name:String(f.get("name")),description:String(f.get("description")),workspace_path:String(f.get("workspace")),repository_url:String(f.get("repo"))});nav(`/projects/${p.id}`)}catch(x){setError(err(x))}finally{setBusy(false)}}
  return <><Header title="项目管理" desc="管理项目空间与 AI 研发资产" action={<Button variant="primary" onClick={()=>setOpen(true)}>＋ 新建项目</Button>}/>{error&&<ErrorBox message={error} retry={load}/>} {loading?<Loading/>:items.length?<div className="project-grid">{items.map(p=><button className="project-card" key={p.id} onClick={()=>nav(`/projects/${p.id}`)}><div><i>{p.name[0]}</i><Status value="running"/></div><h2>{p.name}</h2><p>{p.description||"暂无项目描述"}</p><dl><dt>工作目录</dt><dd>{p.workspace_path||"未配置"}</dd><dt>Git 仓库</dt><dd>{p.repository_url||"未配置"}</dd></dl><footer>进入项目 <b>→</b></footer></button>)}</div>:<Empty title="创建你的第一个项目" detail="配置工作目录后，即可提交产品想法并让 AI 开始研发" action={<Button variant="primary" onClick={()=>setOpen(true)}>新建项目</Button>}/>} {open&&<div className="modal-bg" onMouseDown={()=>setOpen(false)}><form className="modal" onSubmit={create} onMouseDown={e=>e.stopPropagation()}><header><div><h2>新建项目</h2><p>创建 AI 研发工作的基础空间</p></div><button type="button" onClick={()=>setOpen(false)}>×</button></header><label>项目名称 *</label><input name="name" required placeholder="例如：智能客服工作台"/><label>项目描述</label><textarea name="description" placeholder="简要说明项目目标和范围"/><label>本地工作目录 *</label><input name="workspace" required placeholder="/workspace/my-project"/><label>Git 仓库地址</label><input name="repo" placeholder="https://github.com/org/repo.git"/><footer><Button type="button" onClick={()=>setOpen(false)}>取消</Button><Button variant="primary" busy={busy}>创建项目</Button></footer></form></div>}</>;
}

function ProjectPage({id,nav}:{id:string;nav:Nav}) {
  const [project,setProject]=useState<Project>(),[tasks,setTasks]=useState<Task[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const [p,t]=await Promise.all([api.project(id),api.tasks(id)]);setProject(p);setTasks(t)}catch(x){setError(err(x))}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load]);
  if(loading)return <Loading/>;if(!project)return <ErrorBox message={error||"项目不存在"} retry={load}/>;const reqs=project.requirements||[];
  return <><Header title={project.name} desc={project.description||"项目研发空间"} back={()=>nav("/projects")} action={<Button variant="primary" onClick={()=>nav(`/projects/${id}/requirements/new`)}>＋ 提交产品想法</Button>}/><div className="summary"><div><span>项目状态</span><Status value="running"/></div><div><span>工作目录</span><b>{project.workspace_path||"未配置"}</b></div><div><span>Git 仓库</span><b>{project.repository_url||"未配置"}</b></div><div><span>研发任务</span><b>{tasks.length} 项</b></div></div><div className="details"><section className="card"><div className="card-head"><div><h2>需求与生成资产</h2><p>产品想法及 AI 生成结果</p></div></div>{reqs.length?<div className="assets">{reqs.map(r=><button key={r.id} onClick={()=>nav(`/requirements/${r.id}`)}><i>文</i><span><b>{r.title}</b><small>{r.idea}</small></span><Status value={r.status||"completed"}/></button>)}</div>:<Empty title="尚未提交需求" detail="输入产品想法，AI 将生成 PRD、技术方案和任务" action={<Button variant="primary" onClick={()=>nav(`/projects/${id}/requirements/new`)}>提交产品想法</Button>}/>}</section><section className="card"><div className="card-head"><div><h2>研发任务</h2><p>选择任务交给 Agent 执行</p></div></div>{tasks.length?<div className="task-list">{tasks.map(t=><button key={t.id} onClick={()=>{sessionStorage.setItem(`task:${t.id}`,JSON.stringify(t));nav(`/tasks/${t.id}`)}}><i>T-{t.id}</i><span><b>{t.title}</b><small>{t.acceptance_criteria||t.description||"查看任务详情"}</small></span><Status value={t.status}/><em>→</em></button>)}</div>:<Empty title="暂无任务" detail="生成研发资产后，任务会自动出现在这里"/>}</section></div></>;
}

function NewRequirement({projectId,nav}:{projectId:string;nav:Nav}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const r=await api.createRequirement(projectId,{title:String(f.get("title")),idea:String(f.get("idea")),notes:String(f.get("notes"))});nav(`/requirements/${r.id}`)}catch(x){setError(err(x))}finally{setBusy(false)}}
  return <><Header title="提交产品想法" desc="描述你想构建的产品，AI 将生成完整的研发起点" back={()=>nav(`/projects/${projectId}`)}/><form className="card requirement-form" onSubmit={submit}>{error&&<div className="form-error">{error}</div>}<div className="step"><i>1</i><div><h2>描述产品需求</h2><p>清晰描述目标用户、核心场景和期望能力</p></div></div><label>需求标题 *</label><input name="title" required placeholder="例如：为客服团队增加 AI 会话总结"/><label>产品想法 *</label><textarea className="idea" name="idea" required placeholder="我们希望为……用户解决……问题，核心功能包括……"/><label>补充说明</label><textarea name="notes" placeholder="业务约束、参考产品、技术偏好或验收要求"/><div className="ai-note"><b>✦ AI 将为你生成</b><span>产品需求文档（PRD）</span><span>轻量技术方案</span><span>可执行任务清单</span></div><footer><Button type="button" onClick={()=>nav(`/projects/${projectId}`)}>取消</Button><Button variant="primary" busy={busy}>保存并继续</Button></footer></form></>;
}

function RequirementPage({id,nav}:{id:string;nav:Nav}) {
  const [item,setItem]=useState<Requirement>(),[result,setResult]=useState<{prd_markdown:string;technical_markdown:string;tasks:Task[]}>(),[tab,setTab]=useState("prd"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const r=await api.requirement(id);setItem(r);const prd=r.prd_markdown||r.documents?.find(d=>(d.type||d.document_type)==="prd")?.content;const tech=r.technical_markdown||r.documents?.find(d=>(d.type||d.document_type||"").includes("technical"))?.content;if(prd||tech||r.tasks?.length)setResult({prd_markdown:prd||"",technical_markdown:tech||"",tasks:r.tasks||[]})}catch(x){setError(err(x))}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load]);
  async function generate(){setBusy(true);setError("");try{setResult(await api.generate(id))}catch(x){setError(err(x))}finally{setBusy(false)}}
  if(loading)return <Loading/>;if(!item)return <ErrorBox message={error||"需求不存在"} retry={load}/>;const tasks=result?.tasks||item.tasks||[];
  return <><Header title={item.title} desc="需求详情与 AI 生成研发资产" back={()=>nav(`/projects/${item.project_id}`)} action={!result&&<Button variant="primary" busy={busy} onClick={generate}>✦ 生成研发资产</Button>}/>{error&&<ErrorBox message={error}/>}<section className="brief"><div><b>产品想法</b><p>{item.idea}</p></div>{item.notes&&<div><b>补充说明</b><p>{item.notes}</p></div>}</section>{!result?<section className="generate"><i>✦</i><h2>准备生成研发方案</h2><p>AI 将根据产品想法一次性生成简版 PRD、技术方案和可执行任务清单。</p><div><span>PRD</span><span>技术方案</span><span>研发任务</span></div><Button variant="primary large" busy={busy} onClick={generate}>开始 AI 生成</Button><small>演示模式通常在几秒内完成</small></section>:<section className="card result"><nav><button className={tab==="prd"?"active":""} onClick={()=>setTab("prd")}>PRD 文档</button><button className={tab==="tech"?"active":""} onClick={()=>setTab("tech")}>技术方案</button><button className={tab==="tasks"?"active":""} onClick={()=>setTab("tasks")}>任务清单 <em>{tasks.length}</em></button></nav>{tab==="tasks"?<div className="generated-tasks">{tasks.length?tasks.map((t,n)=><button key={t.id||n} onClick={()=>{sessionStorage.setItem(`task:${t.id}`,JSON.stringify(t));nav(`/tasks/${t.id}`)}}><i>{String(n+1).padStart(2,"0")}</i><span><b>{t.title}</b><p>{t.acceptance_criteria||t.description||"点击查看任务并启动 Agent"}</p></span><Status value={t.status}/><em>→</em></button>):<Empty title="任务正在同步" detail="请稍后返回项目详情查看任务"/>}</div>:<article><pre>{tab==="prd"?result.prd_markdown:result.technical_markdown}</pre></article>}</section>}</>;
}

function TaskPage({id,nav}:{id:string;nav:Nav}) {
  const cache=sessionStorage.getItem(`task:${id}`),[task,setTask]=useState<Task|undefined>(()=>cache?JSON.parse(cache):undefined),[mode,setMode]=useState<"mock"|"openhands">("mock"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(!task)api.task(id).then(setTask).catch(x=>setError(err(x)))},[id,task]);async function run(){setBusy(true);setError("");try{const x=await api.runTask(id,mode);nav(`/runs/${x.run_id}`)}catch(x){setError(err(x))}finally{setBusy(false)}}
  if(!task&&!error)return <Loading/>;if(!task)return <ErrorBox message={error||"任务不存在"}/>;
  return <><Header title={task.title} desc={`研发任务 #${id}`} back={()=>history.back()} action={<Status value={task.status}/>} />{error&&<ErrorBox message={error}/>}<div className="task-detail"><section className="card task-copy"><h2>任务目标</h2><p>{task.description||"根据已生成的产品与技术文档完成该开发任务。"}</p><h2>验收标准</h2><div>{task.acceptance_criteria||"功能可运行，代码结构清晰，并通过基础测试。"}</div><h2>Agent 上下文</h2><ul><li>自动读取所属项目工作目录</li><li>注入 PRD、技术方案和当前任务信息</li><li>记录执行日志与修改结果</li></ul></section><aside className="card run-panel"><i>⌘</i><h2>启动开发 Agent</h2><p>选择执行模式，Agent 将在项目工作目录中完成此任务。</p><label className={mode==="mock"?"selected":""}><input type="radio" checked={mode==="mock"} onChange={()=>setMode("mock")}/><span><b>Mock 演示模式</b><small>无需模型配置，快速验证完整流程</small></span></label><label className={mode==="openhands"?"selected":""}><input type="radio" checked={mode==="openhands"} onChange={()=>setMode("openhands")}/><span><b>OpenHands 模式</b><small>调用真实编码 Agent 完成开发</small></span></label><Button variant="primary block large" busy={busy} disabled={["running","queued","completed"].includes(task.status)} onClick={run}>启动 Agent 执行</Button>{(task.latest_run_id||task.agent_run_id)&&<Button variant="block" onClick={()=>nav(`/runs/${task.latest_run_id||task.agent_run_id}`)}>查看最近执行</Button>}</aside></div></>;
}

function RunPage({id,nav}:{id:string;nav:Nav}) {
  const [run,setRun]=useState<AgentRun>(),[events,setEvents]=useState<RunEvent[]>([]),[test,setTest]=useState<TestResult>(),[command,setCommand]=useState(""),[error,setError]=useState(""),[testBusy,setTestBusy]=useState(false),[busy,setBusy]=useState(false);
  const poll=useCallback(async()=>{try{const r=await api.run(id);setRun(r);setEvents(await api.events(id));if(r.test_result)setTest(r.test_result);setError("")}catch(x){setError(err(x))}},[id]);useEffect(()=>{void poll();const timer=setInterval(()=>{if(!run||["queued","running"].includes(run.status))void poll()},2000);return()=>clearInterval(timer)},[poll,run?.status]);
  async function runTest(){setTestBusy(true);try{setTest(await api.testRun(id,command||undefined));await poll()}catch(x){setError(err(x))}finally{setTestBusy(false)}}async function cancel(){setBusy(true);try{await api.cancelRun(id);await poll()}catch(x){setError(err(x))}finally{setBusy(false)}}async function confirm(){if(!run?.task_id)return;setBusy(true);try{await api.confirmTask(String(run.task_id));nav(`/tasks/${run.task_id}`)}catch(x){setError(err(x))}finally{setBusy(false)}}
  if(!run&&!error)return <Loading text="正在连接 Agent..."/>;if(!run)return <ErrorBox message={error} retry={poll}/>;const active=["queued","running"].includes(run.status);
  return <><Header title={`Agent Run #${id}`} desc={`执行模式：${run.mode||"mock"}`} back={()=>run.task_id?nav(`/tasks/${run.task_id}`):history.back()} action={<div className="run-status"><i className={active?"pulse":""}/><Status value={run.status}/></div>}/>{error&&<ErrorBox message={error} retry={poll}/>}<div className="run-grid"><section className="terminal"><header><span><i/><i/><i/></span><b>Agent 实时日志</b><small>{active?"每 2 秒自动刷新":"执行已结束"}</small></header><main>{events.length?events.map(e=><div key={e.id}><time>{new Date(e.created_at).toLocaleTimeString("zh-CN",{hour12:false})}</time><em>{e.event_type}</em><span>{e.message}</span></div>):<p><i className="spinner"/>正在等待 Agent 输出...</p>}</main><footer><span>{events.length} 条事件</span>{active&&<Button variant="danger small" busy={busy} onClick={cancel}>取消执行</Button>}</footer></section><aside className="run-side"><section className="card progress"><h2>执行进度</h2><div><i style={{width:run.status==="queued"?"15%":run.status==="running"?"58%":"100%"}}/></div><p><span>准备环境</span><span>修改代码</span><span>等待确认</span></p></section><section className="card test"><h2>基础测试</h2><p>Agent 完成后运行测试命令，验证修改结果。</p><input value={command} onChange={e=>setCommand(e.target.value)} placeholder="留空使用默认测试命令" disabled={active}/><Button variant="primary block" busy={testBusy} disabled={active} onClick={runTest}>▶ 运行测试</Button>{test&&<div className={test.exit_code===0?"passed":"failed"}><header><b>{test.exit_code===0?"✓ 测试通过":"× 测试失败"}</b><span>退出码 {test.exit_code}</span></header><code>$ {test.command}</code>{test.stdout&&<pre>{test.stdout}</pre>}{test.stderr&&<pre>{test.stderr}</pre>}</div>}</section>{["waiting_confirmation","succeeded"].includes(run.status)&&<section className="card confirm"><i>✓</i><h2>确认任务完成</h2><p>检查日志与测试结果后，将任务标记为已完成。</p><Button variant="success block" busy={busy} onClick={confirm}>确认完成任务</Button></section>}</aside></div></>;
}

function Coming({nav}:{nav:Nav}){const module=new URLSearchParams(location.search).get("module")||"此功能";return <div className="coming"><i>✦</i><b>ROADMAP</b><h1>{module}</h1><p>该能力将在后续版本开放。当前 MVP 专注跑通从产品想法到 Agent 开发与测试的最小闭环。</p><div><span>需求规划中</span><span>敬请期待</span></div><Button variant="primary" onClick={()=>nav("/")}>返回 Dashboard</Button></div>}

export function App(){
  const [route,setRoute]=useState(()=>routeOf(location.pathname)),[user,setUser]=useState<User>(),[checking,setChecking]=useState(true);const nav=useCallback((path:string)=>{history.pushState({},"",path);setRoute(routeOf(path));scrollTo(0,0)},[]);useEffect(()=>{const pop=()=>setRoute(routeOf(location.pathname));addEventListener("popstate",pop);api.me().then(u=>{setUser(u);if(location.pathname==="/login")nav("/")}).catch(()=>{if(location.pathname!=="/login")nav("/login")}).finally(()=>setChecking(false));return()=>removeEventListener("popstate",pop)},[]);
  async function logout(){try{await api.logout()}finally{setUser(undefined);nav("/login")}}if(checking)return <div className="app-loading"><i>F</i><span className="spinner"/><p>正在启动 FlowMind...</p></div>;if(!user||route.name==="login")return <Login done={u=>{setUser(u);nav("/")}}/>;
  const page=route.name==="dashboard"?<Dashboard nav={nav}/>:route.name==="projects"?<Projects nav={nav}/>:route.name==="project"?<ProjectPage id={route.id!} nav={nav}/>:route.name==="newRequirement"?<NewRequirement projectId={route.projectId!} nav={nav}/>:route.name==="requirement"?<RequirementPage id={route.id!} nav={nav}/>:route.name==="task"?<TaskPage id={route.id!} nav={nav}/>:route.name==="run"?<RunPage id={route.id!} nav={nav}/>:<Coming nav={nav}/>;return <Layout user={user} route={route} nav={nav} logout={logout}>{page}</Layout>
}
